<?php

use Illuminate\Database\Seeder;

class SpecialitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \Illuminate\Support\Facades\DB::table('specialities')->insert([
            ['description' => "Alergólogos"],
            ['description' => "Algólogos"],
            ['description' => "Analistas clínicos"],
            ['description' => "Anatomopatólogos"],
            ['description' => "Anestesiólogos"],
            ['description' => "Angiólogos"],
            ['description' => "Audiólogos"],
            ['description' => "Cardiólogos"],
            ['description' => "Cardiólogos pediátricos"],
            ['description' => "Cirujanos cardiovasculares y torácicos"],
            ['description' => "Cirujanos de la mano"],
            ['description' => "Cirujanos estéticos y cosméticos"],
            ['description' => "Cirujanos generales"],
            ['description' => "Cirujanos maxilofaciales"],
            ['description' => "Cirujanos oncológicos"],
            ['description' => "Cirujanos pediátricos"],
            ['description' => "Cirujanos plásticos"],
            ['description' => "Dentistas - Odontólogos"],
            ['description' => "Dermatólogos"],
            ['description' => "Diabetólogos"],
            ['description' => "Endocrinólogos"],
            ['description' => "Endoscopistas"],
            ['description' => "Especialistas en Medicina del Deporte"],
            ['description' => "Especialistas en Medicina del Trabajo"],
            ['description' => "Especialistas en Medicina Integrada"],
            ['description' => "Especialistas en Medicina Nuclear"],
            ['description' => "Especialistas en Medicina Preventiva"],
            ['description' => "Especialistas en Obesidad y Delgadez"],
            ['description' => "Especialistas en Rehabilitación y Medicina Física"],
            ['description' => "Especialistas en Retina Médica y Quirúrgica"],
            ['description' => "Gastroenterólogos"],
            ['description' => "Genetistas"],
            ['description' => "Ginecólogos"],
            ['description' => "Hematólogos"],
            ['description' => "Homeópatas"],
            ['description' => "Infectólogos"],
            ['description' => "Inmunólogos"],
            ['description' => "Internistas"],
            ['description' => "Logopedas"],
            ['description' => "Médicos de familia"],
            ['description' => "Médicos estéticos"],
            ['description' => "Médicos generales"],
            ['description' => "Nefrólogos"],
            ['description' => "Neonatólogos"],
            ['description' => "Neumólogos"],
            ['description' => "Neurocirujanos"],
            ['description' => "Neurofisiólogos"],
            ['description' => "Neurólogos"],
            ['description' => "Nutricionistas"],
            ['description' => "Oftalmólogos"],
            ['description' => "Oncólogos"],
            ['description' => "Oncólogos pediátricos"],
            ['description' => "Optometristas"],
            ['description' => "Ortopedistas"],
            ['description' => "Otorrinolaringólogos"],
            ['description' => "Patólogos"],
            ['description' => "Pediatras"],
            ['description' => "Podiatras"],
            ['description' => "Podólogos"],
            ['description' => "Proctólogos"],
            ['description' => "Profesionales de Medicina Complementaria"],
            ['description' => "Psicólogos"],
            ['description' => "Psicopedagogos"],
            ['description' => "Psiquiatras"],
            ['description' => "Quiroprácticos"],
            ['description' => "Radioterapeutas"],
            ['description' => "Reumatólogos"],
            ['description' => "Sexólogos"],
            ['description' => "Terapeutas ocupacionales"],
            ['description' => "Traumatólogos"],
            ['description' => "Urgenciólogos"],
            ['description' => "Urólogos"],
            ['description' => "Acupuntores"],
            ['description' => "Enfermeros"],
            ['description' => "Enfermeros en Medicina Critica y Terapia Intensiva"],
            ['description' => "Fisioterapeutas"],
            ['description' => "Geriatras"],
            ['description' => "Naturistas"],
            ['description' => "Nutriólogos"],
            ['description' => "Psicoanalistas"],
            ['description' => "Radiólogos"],
            ['description' => "Medicina alternativa"],
            ['description' => "Magnetoterapia"],
            ['description' => "Otra"]
        ]);
    }
}
